# NumPy

---

## Lec:- 05 Indexing & Slicing

#### Indexing
* Acts Similar to python list
* Boolean Indexing
    * Specifying Bolean Array as indexing
* Fancy Indexing
    * Specifying arbitrary array as indexing
    
#### Slicing
* Slices are view of the original array
* Format
    - start:end:step

In [1]:
# Indexing
# import numpy in file
import numpy as np
x= np.array([1,2,3,4,5,6,7,8,9])
x[4]

5

In [2]:
x>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [3]:
x[x>5]

array([6, 7, 8, 9])

In [4]:
x[[1,8,2]]

array([2, 9, 3])

In [5]:
# Slicing
# import numpy in file
import numpy as np
x = np.random.randn(3,3)

In [6]:
x

array([[ 1.32113919, -0.58698631, -0.79972324],
       [ 0.73573925, -0.05440533,  0.06896481],
       [-0.28535446, -1.43457038,  0.65657428]])

In [7]:
x[0]

array([ 1.32113919, -0.58698631, -0.79972324])

In [8]:
x[0][2]

-0.799723237105277

In [9]:
x[1:2:2]

array([[ 0.73573925, -0.05440533,  0.06896481]])

In [10]:
x[::,0:1]

array([[ 1.32113919],
       [ 0.73573925],
       [-0.28535446]])

In [11]:
x=np.ones((5,5))

In [12]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
x[1:-1,1:-1]=0

In [14]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

---

## Lec:- 06 Fast element-wise array functions

There are some functions which can be done on the array elemnts such as sqrt or maximum

In [15]:
import numpy as np
x= np.array([10,9,8,6,11])
x

array([10,  9,  8,  6, 11])

In [16]:
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [17]:
np.power(x,2)

array([100,  81,  64,  36, 121], dtype=int32)

In [18]:
y= np.array([6,2,0,16,7])
y

array([ 6,  2,  0, 16,  7])

In [19]:
np.maximum(x,y)

array([10,  9,  8, 16, 11])

---

## Lec:- 07 np.where

#### np.where()
* A verctarized version of ternry expression x if condition else y
    * condition ? step01 : step02
    * np.where(condition? optionA : optionB) this acts to the complete array

In [20]:
import numpy as np
x= np.array([0,-1,2500,5000,7500,0])
x

array([   0,   -1, 2500, 5000, 7500,    0])

In [21]:
np.where(x<=0,10000,x)

array([10000, 10000,  2500,  5000,  7500, 10000])

In [22]:
np.where(x<=0,"Wrong Data","OK")

array(['Wrong Data', 'Wrong Data', 'OK', 'OK', 'OK', 'Wrong Data'],
      dtype='<U10')

---

## Lec:- 08 Mathematical & Statistical Methods

#### Functions / Methods
* mean()
    * return mean value computed over the array
* comsum()
    * return commulative sum of the arary element
* comprod()
    * returns ther compulative product of the arary element
* sort()
    * sort elements of an array
* unique()
    * returns unique elements

#### Methods for bolean Array
* sum()
    * counting true vales in a bolean array
* any()
    * test if one or more vales in a an array are two
* all()
    * check if every value is true


In [23]:
import numpy as np
x = np.array([10,9,7,10,7])
x

array([10,  9,  7, 10,  7])

In [24]:
x.mean()

8.6

In [25]:
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

In [26]:
x.prod()

44100

In [27]:
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [28]:
np.sort(x)

array([ 7,  7,  9, 10, 10])

In [29]:
np.unique(x)

array([ 7,  9, 10])

In [30]:
y=x>7
y

array([ True,  True, False,  True, False])

In [31]:
y.sum()

3

In [32]:
y.any()

True

In [33]:
y.all()

False