# NumPy

---

## Lec:- 09 File Input Output

* We can save np arrays
    * np.save("filename.npy",array)
    * np.load(filename.npy)
    * np.savez("filename.npz",array1,array2)
* while loading an .npy file returns an dict like object

In [1]:
import numpy as np
x = [1,4,5,7]
y = [8,7,9]

In [2]:
np.save("test1.npy",x)

In [3]:
np.savez("test2.npz",x,y)

In [4]:
loadx=np.load("test1.npy")
loadxy=np.load("test2.npz")

In [5]:
loadx

array([1, 4, 5, 7])

In [6]:
loadxy

---

## Lec:- 10 Linear Algebra Functions

* There are multiple linear algerbra functions available in numpy such as dot product, transpose, trace etc. details can be available from book

In [7]:
import numpy as np
x = np.random.randn(3,2)
y= np.random.randn(2,3)

In [8]:
x

array([[-1.47313045, -2.18764029],
       [ 2.00765947,  0.64994695],
       [-0.58511387, -0.23372154]])

In [9]:
y

array([[-0.99909572, -0.70318761, -0.98557273],
       [-1.225361  , -0.84661072,  0.98870807]])

In [10]:
x.dot(y)

array([[ 4.15244743,  2.8879668 , -0.71106042],
       [-2.80226363, -1.96201332, -1.33608662],
       [ 0.87097802,  0.60931599,  0.34558991]])

In [11]:
x.transpose()

array([[-1.47313045,  2.00765947, -0.58511387],
       [-2.18764029,  0.64994695, -0.23372154]])

In [12]:
x.trace()

-0.8231834998858736

---

## Lec:- 11 Pseudo Random Number

*  we need to randomize data to remove biasness in data set working with ml
* It is impossibel to genrate completly random number as computer genrates random number based on some algo / distribuyion
* So it is known as Pseudo random number as it is based on some type of distribution
* Some distribytion used for genrating random numbers are as follows
    * normal()
    * seed()
    * gamma()
    * uniform()

In [13]:
import numpy as np
np.random.seed(7)
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

---

## Lec:-12 NumPy Advanced Array Manipulations

---