## 4.3.4 Sorting

###### Example01

In [10]:
import numpy as np
arr = np.random.randn(6)
arr

array([-0.01277179,  0.04535512, -0.33918342,  0.7446783 ,  0.53528962,
        0.13035133])

In [11]:
arr.sort()
arr

array([-0.33918342, -0.01277179,  0.04535512,  0.13035133,  0.53528962,
        0.7446783 ])

###### Example02

In [12]:
arr = np.random.randn(5, 3)
arr

array([[ 0.89126022, -0.23421122, -0.48036822],
       [ 0.61781029,  0.83677268, -0.62737096],
       [-0.3279529 , -1.66723143,  1.00741871],
       [-1.23335171, -0.12774491,  1.09104949],
       [ 0.61826694, -0.4903808 , -0.79409672]])

In [13]:
arr.sort(1)

In [14]:
arr

array([[-0.48036822, -0.23421122,  0.89126022],
       [-0.62737096,  0.61781029,  0.83677268],
       [-1.66723143, -0.3279529 ,  1.00741871],
       [-1.23335171, -0.12774491,  1.09104949],
       [-0.79409672, -0.4903808 ,  0.61826694]])

###### Example03

In [15]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))]

-1.7127737906198115