### 4.3.1 Expressing Conditional Logic as Array Operations

###### Example01

In [4]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

###### Example02

In [5]:
arr = np.random.randn(4, 4)
arr

array([[ 1.51690189,  0.86540455,  2.21110697,  0.58017444],
       [ 0.897641  ,  0.57876878,  0.22126197,  0.79049076],
       [-0.95014097,  0.94802081,  1.06150613,  0.0082844 ],
       [ 1.48168596, -0.74621548, -1.28418527, -2.08569605]])

In [6]:
arr > 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True, False, False, False]])

In [7]:
np.where(arr > 0, 2, -2)

array([[ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [-2,  2,  2,  2],
       [ 2, -2, -2, -2]])

In [8]:
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [-0.95014097,  2.        ,  2.        ,  2.        ],
       [ 2.        , -0.74621548, -1.28418527, -2.08569605]])