## 4.1.0 The NumPy ndarray: A Multidimensional Array Object
* numPy store data in the form of mattrix and can perform operation on multiple datasets same as scalor

In [1]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[-0.22240795,  0.26521738,  0.22791081],
       [ 0.32265323,  0.0345867 , -0.55906267]])

In [2]:
data * 10

array([[-2.2240795 ,  2.65217384,  2.27910813],
       [ 3.22653228,  0.34586696, -5.59062671]])

In [3]:
data + data

array([[-0.4448159 ,  0.53043477,  0.45582163],
       [ 0.64530646,  0.06917339, -1.11812534]])

* An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type.
* Every array has a shape, a tuple indicating the size of each dimension a dtype, an object describing the data type of the array

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')