## 4.1.7 Transposing Arrays and Swapping Axes

In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [4]:
arr = np.random.randn(6, 3)
arr

array([[-1.00199776, -0.08111467,  1.63785552],
       [ 1.4008016 ,  0.92438921, -0.53248511],
       [-0.59695918,  0.0107118 ,  1.65986139],
       [ 0.86172832, -0.05656634, -0.85589051],
       [-0.61479127, -0.77564294,  1.23178585],
       [-0.75795239,  1.89878171,  1.6991147 ]])

In [5]:
np.dot(arr.T, arr)

array([[ 5.01764071,  0.35869565, -6.16058737],
       [ 0.35869565,  5.07138346,  1.71193902],
       [-6.16058737,  1.71193902, 10.85808666]])

In [6]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [7]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [8]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [9]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])