## 4.5 Linear Algebra

In [1]:
import numpy as np

![](ten.png)

###### Example01

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [4]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [5]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [7]:
x @ np.ones(3)

array([ 6., 15.])

###### Example02

In [8]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)


array([[  79.42257252,  -44.59920522, -114.19838861,  109.62638786,
         -22.4501559 ],
       [ -44.59920522,   25.49086545,   65.26289898,  -61.94313609,
          12.90015855],
       [-114.19838861,   65.26289898,  168.69077327, -158.81292679,
          33.33875304],
       [ 109.62638786,  -61.94313609, -158.81292679,  151.85545273,
         -31.21855101],
       [ -22.4501559 ,   12.90015855,   33.33875304,  -31.21855101,
           6.94843512]])

In [9]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.06581410e-14,  1.06581410e-14,
        -3.90798505e-14, -7.10542736e-15],
       [ 4.97379915e-14,  1.00000000e+00,  7.10542736e-15,
        -7.10542736e-15,  1.77635684e-15],
       [ 7.10542736e-15,  1.77635684e-15,  1.00000000e+00,
         1.42108547e-14,  9.76996262e-15],
       [ 6.75015599e-14,  9.94759830e-14,  5.68434189e-14,
         1.00000000e+00,  1.50990331e-14],
       [-2.84217094e-14,  0.00000000e+00, -1.42108547e-14,
        -5.68434189e-14,  1.00000000e+00]])

In [10]:
q, r = qr(mat)
q

array([[-0.69382104, -0.24591992, -0.32850853, -0.41294183, -0.42390679],
       [ 0.2046733 , -0.94566892,  0.03392728, -0.05775509,  0.24358248],
       [ 0.10549801,  0.19634413, -0.54544183, -0.50649154,  0.6295067 ],
       [ 0.67670831,  0.01369445, -0.16473464, -0.4089776 , -0.58947277],
       [-0.08750569,  0.08059243,  0.7525203 , -0.63430832,  0.13120126]])

In [11]:
r

array([[-7.60938757,  4.9152943 ,  1.17786574,  8.3800941 , -1.72437371],
       [ 0.        , -7.53455086,  1.2361623 , -1.59444237,  0.9051251 ],
       [ 0.        ,  0.        , -0.9693804 , -0.47722964,  2.61527033],
       [ 0.        ,  0.        ,  0.        , -0.28108227, -1.35415951],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.01888213]])