## 4.1.2 Data Types for ndarrays

In [1]:
import numpy as np

#### 4.1.2 Data Types for ndarrays

In [2]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [3]:
arr1.dtype

dtype('float64')

In [4]:
arr2.dtype

dtype('int32')

![](two.png)

###### DataType conversion

###### Example01

In [5]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.dtype

dtype('int32')

In [7]:
float_arr = arr.astype(np.float64)

In [8]:
float_arr

array([1., 2., 3., 4., 5.])

In [9]:
float_arr.dtype

dtype('float64')

###### Example02

In [10]:
 arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [11]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

###### Example03

In [12]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])