## 4.3.2 Mathematical and Statistical Methods

![](eight.png)

###### example01

In [2]:
import numpy as np
arr = np.random.randn(5, 4)
arr

array([[ 1.00236367,  0.26117277,  0.83046422,  2.25102348],
       [ 1.22770521, -0.38514543, -0.41945229, -0.28145003],
       [-1.30324693,  0.88979624, -1.10261909, -0.61685482],
       [-0.32763343,  1.30611014, -1.70539525,  1.39626843],
       [ 0.30363951,  0.44328741, -0.11026453, -1.1892333 ]])

In [3]:
arr.mean()

0.12352679809022626

In [4]:
np.mean(arr)

0.12352679809022626

In [5]:
arr.sum()

2.4705359618045253

In [6]:
arr.mean(axis=1)

array([ 1.08625603,  0.03541436, -0.53323115,  0.16733747, -0.13814273])

In [7]:
arr.sum(axis=0)

array([ 0.90282803,  2.51522112, -2.50726695,  1.55975376])

###### example02

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [9]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [11]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)