## 4.1.5 Boolean Indexing

In [1]:
import numpy as np

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [3]:
data = np.random.randn(7, 4)
data

array([[-1.46299926,  1.07779233, -0.67944146,  1.34570447],
       [-0.35562981, -1.86374499,  1.07574736,  0.31055391],
       [-0.35551273, -1.33676838,  0.129328  ,  0.42335724],
       [ 1.78053243, -0.23857122,  0.68036222,  0.99510916],
       [-0.19643327, -0.70948917, -1.95359146, -1.22769817],
       [ 0.00845736,  1.38372706,  0.33828509,  0.9174678 ],
       [-0.5662242 ,  2.06790245, -1.65368404,  0.87904251]])

In [4]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [5]:
data[names == 'Bob']

array([[-1.46299926,  1.07779233, -0.67944146,  1.34570447],
       [ 1.78053243, -0.23857122,  0.68036222,  0.99510916]])

In [6]:
data[names == 'Bob', 2:]

array([[-0.67944146,  1.34570447],
       [ 0.68036222,  0.99510916]])

In [7]:
data[names == 'Bob', 3]

array([1.34570447, 0.99510916])

In [8]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [9]:
data[~(names == 'Bob')]

array([[-0.35562981, -1.86374499,  1.07574736,  0.31055391],
       [-0.35551273, -1.33676838,  0.129328  ,  0.42335724],
       [-0.19643327, -0.70948917, -1.95359146, -1.22769817],
       [ 0.00845736,  1.38372706,  0.33828509,  0.9174678 ],
       [-0.5662242 ,  2.06790245, -1.65368404,  0.87904251]])

In [10]:
cond = names == 'Bob'
data[~cond]

array([[-0.35562981, -1.86374499,  1.07574736,  0.31055391],
       [-0.35551273, -1.33676838,  0.129328  ,  0.42335724],
       [-0.19643327, -0.70948917, -1.95359146, -1.22769817],
       [ 0.00845736,  1.38372706,  0.33828509,  0.9174678 ],
       [-0.5662242 ,  2.06790245, -1.65368404,  0.87904251]])

In [11]:
mask = (names == 'Bob') | (names == 'Will')

In [12]:
mask

array([ True, False,  True,  True,  True, False, False])

In [13]:
data[mask]

array([[-1.46299926,  1.07779233, -0.67944146,  1.34570447],
       [-0.35551273, -1.33676838,  0.129328  ,  0.42335724],
       [ 1.78053243, -0.23857122,  0.68036222,  0.99510916],
       [-0.19643327, -0.70948917, -1.95359146, -1.22769817]])

In [14]:
data[data < 0] = 0

In [15]:
data

array([[0.        , 1.07779233, 0.        , 1.34570447],
       [0.        , 0.        , 1.07574736, 0.31055391],
       [0.        , 0.        , 0.129328  , 0.42335724],
       [1.78053243, 0.        , 0.68036222, 0.99510916],
       [0.        , 0.        , 0.        , 0.        ],
       [0.00845736, 1.38372706, 0.33828509, 0.9174678 ],
       [0.        , 2.06790245, 0.        , 0.87904251]])

In [16]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.07574736, 0.31055391],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.00845736, 1.38372706, 0.33828509, 0.9174678 ],
       [0.        , 2.06790245, 0.        , 0.87904251]])