# Assignment: Flowers Recognition
Data : <br>
https://drive.google.com/file/d/1-OX6wn5gA-bJpjPNfSyaYQLz-A-AB_uj/view?usp=sharing

# Dataset Description:

This dataset contains 4242 images of flowers.<br>
The data collection is based on the data flicr, google images, yandex images.<br>
You can use this datastet to recognize plants from the photo.<br>

# Attribute Information:
The pictures are divided into five classes: chamomile, tulip, rose, sunflower, dandelion.<br>
For each class there are about 800 photos. Photos are not high resolution, about 320x240 pixels. <br>
<b>Also explore how to resize images in tensorflow and then resize all the images to a same size. </b> <br>
This is a Multiclass Classification Problem.<br>

# WORKFLOW :
1.Load Data <br>
2.Split into 60 and 40 ratio.<br>
3.Encode labels.<br>
4.Create Model<br>
5.Compilation Step (Note : Its a Multiclass Classification problem , select loss , metrics according to it)<br>
6.Train the Model.<br>
7.If the model gets overfit tune your model by changing the units , No. of layers , epochs , add dropout layer or add 8.Regularizer according to the need .<br>
9.Prediction should be > 85%<br>
10.Evaluation Step<br>
11.Prediction<br>

# Solution

In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import os
import cv2
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from keras import models
from keras import layers
from keras import regularizers

In [2]:
directory = Path("/content/drive/MyDrive/PIAIC_Data/flowers")

In [3]:
flowers = []
features = []
labels = []

In [4]:
# Iterating Over Directory To Extract Sub Directories
for dir in directory.iterdir():
  flowers.append(dir.name)
  print(dir.name)
# Iterating Over Sub Directories To Extract Lables
  for imgpath in dir.iterdir():
    if imgpath.name.endswith("jpg"):
      labels.append(dir.name)
      imgarr = cv2.imread(str(imgpath), cv2.IMREAD_GRAYSCALE)
      imgarr = cv2.resize(imgarr, (150,150))
      features.append(imgarr)

sunflower
tulip
daisy
flowers
rose
dandelion


In [5]:
flowers

['sunflower', 'tulip', 'daisy', 'flowers', 'rose', 'dandelion']

In [6]:
features[0:1]

[array([[195, 162, 133, ..., 192, 192, 192],
        [146, 114,  86, ..., 195, 195, 195],
        [140, 125, 125, ..., 195, 195, 195],
        ...,
        [196, 178, 118, ..., 132, 114,  80],
        [178, 166, 159, ..., 140, 140, 132],
        [ 79, 141, 165, ...,  99, 103, 102]], dtype=uint8)]

In [7]:
print(type(flowers))
print(type(features))
print(type(labels))

<class 'list'>
<class 'list'>
<class 'list'>


In [8]:
# Transform the image array to a numpy type

In [9]:
train = np.asarray(features)

In [10]:
print(train.shape)

(4333, 150, 150)


In [11]:
labels = np.asarray(labels)

In [12]:
labels.shape

(4333,)

In [ ]:
# Extract the labels

In [13]:
label_dummies = pd.get_dummies(labels)

In [14]:
labels =  label_dummies.values.argmax(1)

In [15]:
labels

array([3, 3, 3, ..., 1, 1, 1])

In [16]:
pd.unique(labels)

array([3, 4, 0, 2, 1])

In [17]:
labels.shape

(4333,)

In [20]:
train_data, test_data, train_labels, test_labels=train_test_split(train, labels, test_size=0.4, random_state=1)

In [21]:
print(train_data.shape)

(2599, 150, 150)


In [22]:
print(train_labels.shape)

(2599,)


In [23]:
print(test_data.shape)

(1734, 150, 150)


In [24]:
print(test_labels.shape)

(1734,)


In [25]:
# Normalization

In [28]:
train_images=train_data.reshape((2599,150*150)) 

In [29]:
train_images=train_images.astype('float32') / 255

In [31]:
test_images=test_data.reshape((1734,150*150))

In [32]:
test_images=test_images.astype('float32') / 255

In [33]:
train_labels[3]

3

In [34]:
train_images.shape

(2599, 22500)

In [35]:
train_labels.shape

(2599,)

In [36]:
train_labels = to_categorical(train_labels)

In [37]:
test_labels = to_categorical(test_labels)

In [38]:
train_labels[3]

array([0., 0., 0., 1., 0.], dtype=float32)

In [39]:
network = models.Sequential()

In [40]:
network.add(layers.Dense(512, activation= 'relu', input_shape=(150*150,)))

In [41]:
network.add(layers.Dense(5, activation='softmax'))

In [42]:
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics= ['accuracy'])

In [43]:
history = network.fit(train_images, train_labels, epochs=25, batch_size=128)

Epoch 1/25
21/21 [==============================] - 5s 199ms/step - loss: 61.0819 - accuracy: 0.2148
Epoch 2/25
21/21 [==============================] - 4s 197ms/step - loss: 11.6746 - accuracy: 0.2603
Epoch 3/25
21/21 [==============================] - 4s 194ms/step - loss: 11.9814 - accuracy: 0.2085
Epoch 4/25
21/21 [==============================] - 4s 193ms/step - loss: 9.8730 - accuracy: 0.2573
Epoch 5/25
21/21 [==============================] - 4s 196ms/step - loss: 9.7933 - accuracy: 0.2260
Epoch 6/25
21/21 [==============================] - 4s 195ms/step - loss: 7.5922 - accuracy: 0.2503
Epoch 7/25
21/21 [==============================] - 4s 193ms/step - loss: 7.9517 - accuracy: 0.2450
Epoch 8/25
21/21 [==============================] - 4s 192ms/step - loss: 7.4148 - accuracy: 0.2462
Epoch 9/25
21/21 [==============================] - 4s 193ms/step - loss: 5.8767 - accuracy: 0.2233
Epoch 10/25
21/21 [==============================] - 4s 196ms/step - loss: 6.0560 - accuracy: 0.2

In [45]:
model = models.Sequential()
model.add(layers.Dense(512, activation='relu',kernel_regularizer=regularizers.l2(0.02),input_shape=(150*150,)))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(256,kernel_regularizer=regularizers.l2(0.02), activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(128,kernel_regularizer=regularizers.l2(0.02) ,activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(5, activation='softmax'))

In [46]:
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics= ['accuracy'])

In [47]:
history = network.fit(train_images, train_labels, epochs=25, batch_size=128)

Epoch 1/25
21/21 [==============================] - 4s 196ms/step - loss: 1.6781 - accuracy: 0.3294
Epoch 2/25
21/21 [==============================] - 4s 191ms/step - loss: 1.5860 - accuracy: 0.3624
Epoch 3/25
21/21 [==============================] - 4s 194ms/step - loss: 1.6135 - accuracy: 0.3486
Epoch 4/25
21/21 [==============================] - 4s 193ms/step - loss: 1.7180 - accuracy: 0.3578
Epoch 5/25
21/21 [==============================] - 4s 197ms/step - loss: 1.6073 - accuracy: 0.3417
Epoch 6/25
21/21 [==============================] - 4s 197ms/step - loss: 1.5103 - accuracy: 0.3590
Epoch 7/25
21/21 [==============================] - 4s 193ms/step - loss: 1.4633 - accuracy: 0.3855
Epoch 8/25
21/21 [==============================] - 4s 199ms/step - loss: 1.5572 - accuracy: 0.3624
Epoch 9/25
21/21 [==============================] - 4s 194ms/step - loss: 1.4527 - accuracy: 0.3936
Epoch 10/25
21/21 [==============================] - 4s 197ms/step - loss: 1.4342 - accuracy: 0.3913

In [48]:
model = models.Sequential()
model.add(layers.Dense(1024, activation='relu',kernel_regularizer=regularizers.l2(0.02),input_shape=(150*150,)))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(512,kernel_regularizer=regularizers.l2(0.02), activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(256,kernel_regularizer=regularizers.l2(0.02) ,activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(128,kernel_regularizer=regularizers.l2(0.02) ,activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(64,kernel_regularizer=regularizers.l2(0.02) ,activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(32,kernel_regularizer=regularizers.l2(0.02) ,activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(16,kernel_regularizer=regularizers.l2(0.02) ,activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(8,kernel_regularizer=regularizers.l2(0.02) ,activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(5, activation='softmax'))

In [49]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics= ['accuracy'])

In [50]:
history = network.fit(train_images, train_labels, epochs=50, batch_size=128)

Epoch 1/50
21/21 [==============================] - 4s 196ms/step - loss: 1.2996 - accuracy: 0.4779
Epoch 2/50
21/21 [==============================] - 4s 193ms/step - loss: 1.2762 - accuracy: 0.5010
Epoch 3/50
21/21 [==============================] - 4s 194ms/step - loss: 1.2210 - accuracy: 0.4906
Epoch 4/50
21/21 [==============================] - 4s 199ms/step - loss: 1.2357 - accuracy: 0.5017
Epoch 5/50
21/21 [==============================] - 4s 194ms/step - loss: 1.2304 - accuracy: 0.5040
Epoch 6/50
21/21 [==============================] - 4s 196ms/step - loss: 1.2691 - accuracy: 0.5010
Epoch 7/50
21/21 [==============================] - 4s 198ms/step - loss: 1.2859 - accuracy: 0.4967
Epoch 8/50
21/21 [==============================] - 4s 201ms/step - loss: 1.1819 - accuracy: 0.5248
Epoch 9/50
21/21 [==============================] - 4s 199ms/step - loss: 1.1643 - accuracy: 0.5210
Epoch 10/50
21/21 [==============================] - 4s 198ms/step - loss: 1.2061 - accuracy: 0.5206

In [52]:
model = models.Sequential()
model.add(layers.Dense(1024, activation='relu',input_shape=(150*150,)))
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(8, activation='relu'))
model.add(layers.Dense(5, activation='softmax'))

In [53]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics= ['accuracy'])

In [54]:
history = network.fit(train_images, train_labels, epochs=200, batch_size=64)

Epoch 1/200
41/41 [==============================] - 6s 151ms/step - loss: 0.9578 - accuracy: 0.6491
Epoch 2/200
41/41 [==============================] - 6s 150ms/step - loss: 0.9686 - accuracy: 0.6503
Epoch 3/200
41/41 [==============================] - 6s 149ms/step - loss: 0.8692 - accuracy: 0.6780
Epoch 4/200
41/41 [==============================] - 6s 151ms/step - loss: 0.8935 - accuracy: 0.6776
Epoch 5/200
41/41 [==============================] - 6s 151ms/step - loss: 0.9086 - accuracy: 0.6664
Epoch 6/200
41/41 [==============================] - 6s 151ms/step - loss: 0.8688 - accuracy: 0.6753
Epoch 7/200
41/41 [==============================] - 6s 152ms/step - loss: 0.8915 - accuracy: 0.6741
Epoch 8/200
41/41 [==============================] - 6s 150ms/step - loss: 0.9510 - accuracy: 0.6722
Epoch 9/200
41/41 [==============================] - 6s 151ms/step - loss: 0.8302 - accuracy: 0.6987
Epoch 10/200
41/41 [==============================] - 6s 150ms/step - loss: 0.8536 - accura

In [55]:
model = models.Sequential()
model.add(layers.Dense(1024, activation='tanh',input_shape=(150*150,)))
model.add(layers.Dense(512, activation='tanh'))
model.add(layers.Dense(256, activation='tanh'))
model.add(layers.Dense(128, activation='tanh'))
model.add(layers.Dense(64, activation='tanh'))
model.add(layers.Dense(32, activation='tanh'))
model.add(layers.Dense(16, activation='tanh'))
model.add(layers.Dense(8, activation='tanh'))
model.add(layers.Dense(5, activation='softmax'))

In [56]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics= ['accuracy'])

In [57]:
history = network.fit(train_images, train_labels, epochs=100, batch_size=128)

Epoch 1/100
21/21 [==============================] - 4s 193ms/step - loss: 1.2144 - accuracy: 0.8657
Epoch 2/100
21/21 [==============================] - 4s 193ms/step - loss: 0.0863 - accuracy: 0.9665
Epoch 3/100
21/21 [==============================] - 4s 191ms/step - loss: 0.4671 - accuracy: 0.8992
Epoch 4/100
21/21 [==============================] - 4s 194ms/step - loss: 0.0801 - accuracy: 0.9673
Epoch 5/100
21/21 [==============================] - 4s 194ms/step - loss: 0.4809 - accuracy: 0.8888
Epoch 6/100
21/21 [==============================] - 4s 193ms/step - loss: 0.1574 - accuracy: 0.9442
Epoch 7/100
21/21 [==============================] - 4s 195ms/step - loss: 0.3408 - accuracy: 0.9050
Epoch 8/100
21/21 [==============================] - 4s 197ms/step - loss: 0.1267 - accuracy: 0.9546
Epoch 9/100
21/21 [==============================] - 4s 193ms/step - loss: 0.2571 - accuracy: 0.9273
Epoch 10/100
21/21 [==============================] - 4s 192ms/step - loss: 0.6380 - accura

In [58]:
test_loss, test_accuracy = model.evaluate(test_images,test_labels)
print("test accuracy is :", test_accuracy)

55/55 [==============================] - 3s 50ms/step - loss: 1.5926 - accuracy: 0.2107
test accuracy is : 0.22433678805828094


In [59]:
model = models.Sequential()
model.add(layers.Dense(1024, activation='relu',input_shape=(150*150,)))
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(5, activation='softmax'))

In [60]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics= ['accuracy'])

In [61]:
history = network.fit(train_images, train_labels, epochs=100, batch_size=128)

Epoch 1/100
21/21 [==============================] - 4s 193ms/step - loss: 0.0770 - accuracy: 0.9735
Epoch 2/100
21/21 [==============================] - 4s 193ms/step - loss: 0.2217 - accuracy: 0.9450
Epoch 3/100
21/21 [==============================] - 4s 190ms/step - loss: 0.3885 - accuracy: 0.9073
Epoch 4/100
21/21 [==============================] - 4s 191ms/step - loss: 0.1575 - accuracy: 0.9611
Epoch 5/100
21/21 [==============================] - 4s 192ms/step - loss: 1.1517 - accuracy: 0.8580
Epoch 6/100
21/21 [==============================] - 4s 194ms/step - loss: 0.0574 - accuracy: 0.9781
Epoch 7/100
21/21 [==============================] - 4s 195ms/step - loss: 0.3983 - accuracy: 0.9096
Epoch 8/100
21/21 [==============================] - 4s 193ms/step - loss: 0.3749 - accuracy: 0.9261
Epoch 9/100
21/21 [==============================] - 4s 192ms/step - loss: 0.0839 - accuracy: 0.9708
Epoch 10/100
21/21 [==============================] - 4s 194ms/step - loss: 0.2631 - accura

In [62]:
test_loss, test_accuracy = model.evaluate(test_images,test_labels)
print("test accuracy is :", test_accuracy)

55/55 [==============================] - 3s 44ms/step - loss: 1.7191 - accuracy: 0.1724
test accuracy is : 0.18281430006027222
