# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
b2 = np.zeros(10)
print("Null vector of size 10 = ")
print(b2)

Null vector of size 10 = 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
b3 = np.arange(10,50)
print("Vector with values ranging from 10 to 49 = ")
print(b3)

Vector with values ranging from 10 to 49 = 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [4]:
print("Shape of array in question 3")
print(b3.shape)

Shape of array in question 3
(40,)


5. Print the type of the previous array in question 3

In [5]:
print("Type of array in question 3")
print(b3.dtype)

Type of array in question 3
int32


6. Print the numpy version and the configuration


In [6]:
print("======")
print("numPy version = ",np.__version__)
print("======")
print("numPy Configration = ",np.show_config())

numPy version =  1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.1

7. Print the dimension of the array in question 3


In [7]:
print("Dimensions of array in question 3 = ")
print(b3.ndim)

Dimensions of array in question 3 = 
1


8. Create a boolean array with all the True values

In [8]:
b8 = np.ones((5), dtype=bool)
print("Boolean array with all the True values = ")
print(b8)

Boolean array with all the True values = 
[ True  True  True  True  True]


9. Create a two dimensional array




In [9]:
b9 = np.ndarray((2,2),dtype=bool)
print("Two dimensional array = ")
print(b9)

Two dimensional array = 
[[ True False]
 [False False]]


10. Create a three dimensional array



In [10]:
ten = np.zeros((2, 2, 2))
print("Three dimensional array = ")
print(ten)

Three dimensional array = 
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
e1 = np.arange(0,10)
print("original Vector = ",e1)
e1s = e1[::-1]
print("reversed Vector = ",e1s)

original Vector =  [0 1 2 3 4 5 6 7 8 9]
reversed Vector =  [9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
import numpy as np
e12 = np.zeros(10)
print("original vector = ",e12)
e12[4] = 1
print("updated  vector = ",e12)

original vector =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
updated  vector =  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
e13 = np.eye(3)
print("Identity Matrix of 3*3 = ")
print(e13)

Identity Matrix of 3*3 = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float64)
print("Array with build in Data Type = ",arr)
print("Array with Float Data  Type  =  ",float_arr)

Array with build in Data Type =  [1 2 3 4 5]
Array with Float Data  Type  =   [1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
print("arr1 = ")
print(arr1)
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print("arr2 = ")
print(arr2)
z = arr1*arr2
print("arr1*arr2 = ")
print(z)

arr1 = 
[[1. 2. 3.]
 [4. 5. 6.]]
arr2 = 
[[ 0.  4.  1.]
 [ 7.  2. 12.]]
arr1*arr2 = 
[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
a = np.arange(0,10)
print("origianl array = ",a)
b= a[a % 2 == 1]
print("odd numb array = ",b)

origianl array =  [0 1 2 3 4 5 6 7 8 9]
odd numb array =  [1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [18]:
print("origianl array = ",a)
a[a % 2 == 1]=-1
print("replaced array = ",a)

origianl array =  [0 1 2 3 4 5 6 7 8 9]
replaced array =  [ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
print("original Array = ",arr)
arr[5:9]=12
print("Modified Array = ",arr)

original Array =  [0 1 2 3 4 5 6 7 8 9]
Modified Array =  [ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [20]:
x = np.ones((5,5))
print("Original array = ")
print(x)
print("")
print("Updated array = ")
x[1:-1,1:-1] = 0
print(x)

Original array = 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Updated array = 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print("Original array = ")
print(arr2d)
arr2d[1:2,1:2]=12
print("Updated array = ")
print(arr2d)

Original array = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Updated array = 
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Original array = ")
print(arr3d)
arr3d[0][0] = 64
print("Updated array = ")
print(arr3d)

Original array = 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Updated array = 
[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
array1 = np.arange(10).reshape(2,5)
print("2D array = ")
print(array1)
print("")
print("ist 1D array = ")
print(array1[0])

2D array = 
[[0 1 2 3 4]
 [5 6 7 8 9]]

ist 1D array = 
[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
array1 = np.arange(10).reshape(2,5)
print("2D array = ")
print(array1)
print("")
print("2nd value from 2nd 1-D array = ")
print(array1[1][1])

2D array = 
[[0 1 2 3 4]
 [5 6 7 8 9]]

2nd value from 2nd 1-D array = 
6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
array1 = np.arange(9).reshape(3,3)
print("2D array = ")
print(array1)
print("")
print("third column but only the first two rows = ")
print(array1[0:2,2:4])

2D array = 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

third column but only the first two rows = 
[[2]
 [5]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr = np.random.randn(10,10)
print("origional array = ")
print(arr)
print("")
print("")
print("min Value = ", np.min(arr))
print("max Value = ", np.max(arr))

origional array = 
[[ 0.36783608  1.10694549  0.04803429  0.56617979 -0.36761706 -0.15609613
  -1.23481655 -1.34416771  0.45205276 -0.04542036]
 [ 0.9277796   1.08595226 -0.81357941 -0.04685747  0.87342279  0.65296373
  -0.86782763 -0.01413864  1.03224626 -0.91747002]
 [-0.63405013 -0.96485115 -0.01470436 -2.330733   -1.28247854  1.49121275
  -0.84685619 -0.37033217 -0.38498662 -0.37201461]
 [-0.6357873  -0.15098127  0.14966054  0.36049897  0.03742728 -1.63037612
  -1.24731376  1.59688808  0.87099613 -0.76711064]
 [ 0.26787188 -0.12509843  0.28756225 -1.55226217 -2.0911713  -0.09770444
   0.63485476 -0.53163855 -0.51600055 -0.19562742]
 [ 0.68470918  1.67965104  0.95358119  1.24213612 -0.1488271   0.67646218
   0.44562793 -1.36858912 -0.1726797  -3.35066768]
 [ 0.0318832   2.40728872  0.69349681 -0.85544438 -0.91007687 -1.29248062
   0.44024959 -0.19271508  1.13910867 -2.6265644 ]
 [-1.05574143 -1.03775433  1.11030988  0.92338266  0.35034902  0.360002
   2.07971631  0.4790959   0.85815

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("a = ",a)
print("b = ",b)
print("common = " , np.intersect1d(a, b))
print(a==b)

a =  [1 2 3 2 3 4 3 4 5 6]
b =  [ 7  2 10  2  7  4  9  4  9  8]
common =  [2 4]
[False  True False  True False  True False  True False False]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Names = ")
print(names)
print("")
print("Data = ")
print(data)
print("")
print("Array data where the values from array names are not equal to Will")
print(data[names != 'Will'])

Names = 
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Data = 
[[ 0.35021171 -0.45808289  1.4377424  -1.26201292]
 [-0.66509677 -0.51062355 -1.07968425  0.96610632]
 [-0.52521551 -0.18944585 -0.84406227 -1.76988714]
 [ 0.70922293  1.33289187 -0.83855569 -0.70745503]
 [ 0.55650196  0.99743331 -0.04648509 -0.22542041]
 [ 1.00519937 -1.02218251 -2.47152447 -0.99414501]
 [-0.6817762  -1.08812877 -0.26083273 -0.35420265]]

Array data where the values from array names are not equal to Will
[[ 0.35021171 -0.45808289  1.4377424  -1.26201292]
 [-0.66509677 -0.51062355 -1.07968425  0.96610632]
 [ 0.70922293  1.33289187 -0.83855569 -0.70745503]
 [ 1.00519937 -1.02218251 -2.47152447 -0.99414501]
 [-0.6817762  -1.08812877 -0.26083273 -0.35420265]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Names = ")
print(names)
print("")
print("Data = ")
print(data)
print("")
print("Array data where the values from array names are not equal to Will and JOE")
print(data[(names != 'Will') & (names != 'Joe')])

Names = 
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Data = 
[[ 0.89651001  0.74502996  0.27334146 -1.0849144 ]
 [-0.14408223 -1.33589474 -1.98871681 -0.26193961]
 [-1.1299642  -0.85685898  0.12565702  0.42172514]
 [-0.80959745 -0.01981705  0.735401   -1.38206629]
 [-1.61886924 -0.57824004  0.30684188 -1.69577205]
 [-0.76926959 -0.19267941 -1.12893317 -0.81790412]
 [ 0.89704646 -0.08307513 -0.25504751 -1.08291282]]

Array data where the values from array names are not equal to Will and JOE
[[ 0.89651001  0.74502996  0.27334146 -1.0849144 ]
 [-0.80959745 -0.01981705  0.735401   -1.38206629]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
array1 = (np.arange(1,16).reshape(5,3)).astype(np.float64)
print("2D array of shape 5x3 to contain decimal numbers between 1 and 15 = ")
print(array1)

2D array of shape 5x3 to contain decimal numbers between 1 and 15 = 
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
array1 = (np.arange(1,17).reshape(2,2,4)).astype(np.float64)
print("array of shape (2, 2, 4) with decimal numbers between 1 to 16 = ")
print(array1)

array of shape (2, 2, 4) with decimal numbers between 1 to 16 = 
[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


33. Swap axes of the array you created in Question 32

In [33]:
print("Original Array")
print(array1)
print("Swapped axis")
np.swapaxes(array1,0,1)

Original Array
[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]
Swapped axis


array([[[ 1.,  2.,  3.,  4.],
        [ 9., 10., 11., 12.]],

       [[ 5.,  6.,  7.,  8.],
        [13., 14., 15., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
r = np.arange(0,1,.1)
r1 = np.sqrt(r)
r3=np.where(r1<0.5,0,r1)
print("Sqrt of array")
print(r1)
print("")
print("Array of size 10")
print(r)
print("")
print("Modified array")
print(r3)

Sqrt of array
[0.         0.31622777 0.4472136  0.54772256 0.63245553 0.70710678
 0.77459667 0.83666003 0.89442719 0.9486833 ]

Array of size 10
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

Modified array
[0.         0.         0.         0.54772256 0.63245553 0.70710678
 0.77459667 0.83666003 0.89442719 0.9486833 ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
a = np.random.randn(12)
b = np.random.randn(12)
c = np.maximum(a,b)
print("Array 01")
print(a)
print("")
print("Array 02")
print(b)
print("")
print("Modified Array")
print(c)

Array 01
[ 0.20123525 -0.60426746 -0.86981923 -2.39368742  0.16231702  0.66799263
 -0.07994912  0.10400966 -1.5462936   1.03278192 -1.11389618 -0.20214557]

Array 02
[-0.51277545  0.095323    2.1906018   1.0593845  -1.0918515  -1.10700646
  1.26797409  0.59075762 -2.13804988 -1.02308185 -0.57478381 -0.52321857]

Modified Array
[ 0.20123525  0.095323    2.1906018   1.0593845   0.16231702  0.66799263
  1.26797409  0.59075762 -1.5462936   1.03278192 -0.57478381 -0.20214557]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print("Original array")
print(names)
unames=np.sort(np.unique(names))
print("Sorted Unique Elements")
print(unames)

Original array
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
Sorted Unique Elements
['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print("Array a = ")
print(a)
print("Array b = ")
print(b)
print("Array a with array b elements removed = ")
result = np.setdiff1d(a, b)
print(result)

Array a = 
[1 2 3 4 5]
Array b = 
[5 6 7 8 9]
Array a with array b elements removed = 
[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print("Origional Array")
print(sampleArray)
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print("Modified Array")
sampleArray = np.insert(sampleArray , 1, newColumn, axis = 1) 
print (sampleArray)

Origional Array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Modified Array
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print("Array x")
print(x)
print("Array y")
print(y)
print("x.y")
np.dot(x, y)

Array x
[[1. 2. 3.]
 [4. 5. 6.]]
Array y
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
x.y


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
x = np.random.randn(20)
print("Matrix of 20 values")
print(x)
print("Cumulative sum")
y = np.cumsum(x)
print(y)

Matrix of 20 values
[ 0.83553242  0.9598661   0.49011915 -1.77118396 -0.91410333 -1.8876767
  0.91471918 -0.4443233  -0.06512546  0.26218308 -1.71643381  0.93205616
  1.43809992  1.26552986  1.6995629  -1.23575753 -1.75906316  0.22811445
 -1.5259825  -0.74862877]
Cumulative sum
[ 0.83553242  1.79539851  2.28551767  0.5143337  -0.39976963 -2.28744633
 -1.37272716 -1.81705045 -1.88217592 -1.61999283 -3.33642665 -2.40437048
 -0.96627056  0.2992593   1.9988222   0.76306467 -0.99599849 -0.76788405
 -2.29386655 -3.04249532]
