# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr1=np.arange(10)
arr2 = arr1.reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr1 = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1]])
arr3 = np.vstack((arr1,arr2))
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
arr1 = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1],
                [1, 1, 1, 1, 1]])
arr3 = np.hstack((arr1,arr2))
arr3

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
arr1 = np.arange(0,10).reshape(5,2)
arr2 = arr1.flatten()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
arr1 = np.arange(0,15).reshape(5,3)
arr2 = arr1.ravel()
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
arr1 = np.arange(0,15).reshape(5,3)
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
arr1 = np.arange(0,25).reshape(5,5)
print("Actual Array")
print(arr1)
print("Squared array")
print(np.square(arr1))

Actual Array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Squared array
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [8]:
arr1 = np.arange(0,30).reshape(5,6)
print("Actual Array")
print(arr1)
print("Mean of array")
print(np.mean(arr1))

Actual Array
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Mean of array
14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
print("Actual Array")
print(arr1)
print("Standard deviation of Array")
print(np.std(arr1))

Actual Array
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Standard deviation of Array
8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [10]:
print("Actual Array")
print(arr1)
print("Median of Array")
print(np.median(arr1))

Actual Array
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Median of Array
14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [11]:

print("Original Array")
print (arr1)
print("Transpose of Array")
print(np.transpose(arr1))

Original Array
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Transpose of Array
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
arr1 = np.arange(0,16).reshape(4,4)
print("Original array")
print(arr1)
print("Sum of diagonal elements")
print(np.trace(arr1))

Original array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sum of diagonal elements
30


## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
print("Original array")
print(arr1)
print("determinant of array")
print(np.linalg.det(arr1))

Original array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
determinant of array
0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
arr1 = np.random.randn(5,5)
print("Original Array")
print (arr1)
print("5th percentile of array = ",np.percentile(arr1, 5))
print("95th percentile of array = ",np.percentile(arr1, 95))


Original Array
[[-0.48477204  0.65034645 -0.61230933  0.69411424  1.55442987]
 [-1.83346516 -0.876698    1.44582085 -0.22705624  1.6407015 ]
 [-0.4958615   0.0088175   0.0119433   1.36025052 -0.59691294]
 [ 0.85549155 -0.14938838 -0.19778125  0.20488114  0.04656378]
 [ 1.7538838  -0.14618541  0.18815104  0.6363072   0.25885186]]
5th percentile of array =  -0.8238202636790711
95th percentile of array =  1.6234471706323448


## Question:15

### How to find if a given array has any null values?

In [15]:
# To find if a array has any nullvalue use any() to find. if it returns true there is some null value in the array
arr1 = np.arange(10)
arr1.any()

True