# NumPy

---

## Lec:-13 Reshape
* We can reshape any array with only condition to have have number of elements
    * -C : Row Major Order
    * Fortran order: Column major order
    * Specifying -1 for reshape() means the value used for that dimension will be inferred from the data
    * ravel() or flatten() i.e. flattering to one dimension

In [1]:
import numpy as np
x = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
# row major order
x.reshape((4,3),order='c')

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
# column major order
x.reshape((4,3),order='f')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [4]:
x = np.random.randn(4,5)
x

array([[ 1.71361441,  0.74349532, -0.46083274,  3.12853028,  0.40215516],
       [ 0.50410425, -1.4286596 ,  0.01613559, -1.29851368,  1.83746007],
       [ 1.15669012, -0.65836712, -0.01435723, -0.26896683, -0.03015764],
       [ 0.82161798, -1.44713058,  0.4996552 ,  0.06881274,  0.97712131]])

In [5]:
x.reshape(2,2,5)

array([[[ 1.71361441,  0.74349532, -0.46083274,  3.12853028,
          0.40215516],
        [ 0.50410425, -1.4286596 ,  0.01613559, -1.29851368,
          1.83746007]],

       [[ 1.15669012, -0.65836712, -0.01435723, -0.26896683,
         -0.03015764],
        [ 0.82161798, -1.44713058,  0.4996552 ,  0.06881274,
          0.97712131]]])

In [6]:
x.reshape((2,2,5),order="F")

array([[[ 1.71361441,  0.74349532, -0.46083274,  3.12853028,
          0.40215516],
        [ 1.15669012, -0.65836712, -0.01435723, -0.26896683,
         -0.03015764]],

       [[ 0.50410425, -1.4286596 ,  0.01613559, -1.29851368,
          1.83746007],
        [ 0.82161798, -1.44713058,  0.4996552 ,  0.06881274,
          0.97712131]]])

In [7]:
x.reshape(2,2,-1)

array([[[ 1.71361441,  0.74349532, -0.46083274,  3.12853028,
          0.40215516],
        [ 0.50410425, -1.4286596 ,  0.01613559, -1.29851368,
          1.83746007]],

       [[ 1.15669012, -0.65836712, -0.01435723, -0.26896683,
         -0.03015764],
        [ 0.82161798, -1.44713058,  0.4996552 ,  0.06881274,
          0.97712131]]])

In [8]:
x

array([[ 1.71361441,  0.74349532, -0.46083274,  3.12853028,  0.40215516],
       [ 0.50410425, -1.4286596 ,  0.01613559, -1.29851368,  1.83746007],
       [ 1.15669012, -0.65836712, -0.01435723, -0.26896683, -0.03015764],
       [ 0.82161798, -1.44713058,  0.4996552 ,  0.06881274,  0.97712131]])

In [9]:
x.ravel()

array([ 1.71361441,  0.74349532, -0.46083274,  3.12853028,  0.40215516,
        0.50410425, -1.4286596 ,  0.01613559, -1.29851368,  1.83746007,
        1.15669012, -0.65836712, -0.01435723, -0.26896683, -0.03015764,
        0.82161798, -1.44713058,  0.4996552 ,  0.06881274,  0.97712131])

In [10]:
x.flatten()

array([ 1.71361441,  0.74349532, -0.46083274,  3.12853028,  0.40215516,
        0.50410425, -1.4286596 ,  0.01613559, -1.29851368,  1.83746007,
        1.15669012, -0.65836712, -0.01435723, -0.26896683, -0.03015764,
        0.82161798, -1.44713058,  0.4996552 ,  0.06881274,  0.97712131])

---

## Lec:-14 Concatination
* concatinate()
    * Takes a sequence of arrays and join them together in order along the input axis
    * vStack
        * Stack arrays row wise (along axis 0)
    * hStack
        * Stack arrays column wise (along axis 1)

In [11]:
import numpy as np
x = [[1,3,5],[7,9,0]]
arry1 = np.array(x)
arry1

array([[1, 3, 5],
       [7, 9, 0]])

In [12]:
y = [[11,13,15],[17,19,10]]
arry2 = np.array(y)
arry2

array([[11, 13, 15],
       [17, 19, 10]])

In [13]:
np.concatenate((arry1,arry2),axis=0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [14]:
np.concatenate((arry1,arry2),axis=1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [15]:
np.vstack((arry1,arry2))

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [16]:
np.hstack((arry1,arry2))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

---

## Lec:-15 Split
* Split Slices apart and array into multiple arrays along an axis

In [17]:
import numpy as np
x = [1,4,5,6,7,9,1,4]
x

[1, 4, 5, 6, 7, 9, 1, 4]

In [18]:
d = np.array(x)
d

array([1, 4, 5, 6, 7, 9, 1, 4])

In [19]:
np.split(d,[4,5])

[array([1, 4, 5, 6]), array([7]), array([9, 1, 4])]

In [20]:
x = [[1,4,5,6,7,9,1,4],[11,14,15,16,17,19,11,14]]
x

[[1, 4, 5, 6, 7, 9, 1, 4], [11, 14, 15, 16, 17, 19, 11, 14]]

In [21]:
d = np.array(x)
d

array([[ 1,  4,  5,  6,  7,  9,  1,  4],
       [11, 14, 15, 16, 17, 19, 11, 14]])

In [22]:
np.split(d,[4,6],axis=1)

[array([[ 1,  4,  5,  6],
        [11, 14, 15, 16]]),
 array([[ 7,  9],
        [17, 19]]),
 array([[ 1,  4],
        [11, 14]])]

---

## Lec:-16 Tile & Repeat
* repeat()
    * repeat replicate each element in an array some number of times, producing a larger array
    * if you pass an array of integers each elements can be repeated a number of times
* tile()
    * Tile is the shortcut for stacking copies of an array along an axis

In [23]:
import numpy as np
d = np.array([1,5,7,8])
d

array([1, 5, 7, 8])

In [24]:
np.repeat(d,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [25]:
np.tile(d,2)

array([1, 5, 7, 8, 1, 5, 7, 8])

---

## Conclusion
* Covered ndarray: creating, indexing, slicing, I/O, linear algebra, random number generation
* Advance Concept such as concatenation, split, repeat, tile
* Other advance concepts such as broadcasting describe how arethmatics works b/w arrays of different shapes 
* Sorting