# NumPy

-----------------

## Lec:- 01 NumPy Introduction

#### Introduction to NumPy
* Numerical Python
* A lot of libraries of AI are based on numpy
* NumPy is actually based on n-dimensional array
* usefull for fast operations on entire arrays
* have ability to read and write
* bucnh of linear algerbra opertions

#### Why NumPy
* Data is stored contigous inother store data in a sequence
* Can perform complex operations on a single command

#### Installation
* Pre Installed in Anaconda
* pip install numpy

***

## Lec:- 02 NumPy vs Python List

#### Fast opertion in NumPy

* Let make an array of one million numbers and a list of same size
* Multiply every elemnt of list and array with a digit for ten times
* Calculate time for each process
* Comapre Results

In [1]:
# import numpy in the file
import numpy as np

# Define a list of one million number
l = range(10_00_000)

# Define an array of one million numbers
d = np.arange(10_00_000)

In [2]:
# Multiply each element of list with a number for 10 times and find time for the procees to complete
%time for i in range(1,10) : r=[x*2 for x in l]

Wall time: 1.36 s


In [3]:
# Multiply each element of array with a number for 10 times and find time for the procees to complete
%time for i in range(1,10) : r=d*2

Wall time: 58.9 ms


***

## Lec:- 03 A Multidimensional Array Object

#### ndArray
* Fast flexible container for storing large dataset in python
* Homegenious data

In [4]:
# import numpy in file
import numpy as np

# ndArray of zeros
a = np.zeros([4,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
# ndArray of ones
b = np.ones([4,4])
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# ndArray of empty
c = np.empty([2,2])
c
# this makes an array of junk data

array([[0., 0.],
       [0., 0.]])

In [7]:
# we can convert a list into an array
z = [1,2,3,4,5,6,7,8]
d = np.array(z)
d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
# to genrate a range of numbers with desired steps
e = np.arange(1,100,10)
e

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [9]:
# find shape of any array let view shapes of above arrays
print("Shape of a = ", a.shape)
print("Shape of b = ", b.shape)
print("Shape of c = ", c.shape)
print("Shape of d = ", d.shape)
print("Shape of e = ", e.shape)

Shape of a =  (4, 4)
Shape of b =  (4, 4)
Shape of c =  (2, 2)
Shape of d =  (8,)
Shape of e =  (10,)


In [10]:
# we can reshape a predeifned array
f = np.ones((4,4))
print("Actual = ", f)
g= f.reshape(2,2,4,1)
print("Re-Shaped = ", g)

Actual =  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Re-Shaped =  [[[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]]


In [11]:
# Find Data type of array
# thre are multiple data types
g.dtype

dtype('float64')

In [12]:
# find dimention of an array
print("Dim of f = ", f.ndim)
print("Dim of g = ", g.ndim)

Dim of f =  2
Dim of g =  4


---

## Lec:- 04 Arithmetic with ndarray

#### Vectorization
* Batch operation on data can be done without using for loops
* operation between arrays of same size defines operation b/w each elemt
* operation with scalr is a operation with every elemt

In [13]:
# let define an array
import numpy as np
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
print("arr = ", arr)

arr =  [[1. 2. 3.]
 [4. 5. 6.]]


In [14]:
# multiplying two arrays (multiply each elemt with corresponding one)
# Same goes with diviosn
arr1= arr * arr
print("arr * arr = ", arr1)

arr * arr =  [[ 1.  4.  9.]
 [16. 25. 36.]]


In [15]:
# adding two arrays (Add each elemt with corresponding one)
# Same goes with subtraction
arr2= arr + arr
print("arr + arr = ", arr1)

arr + arr =  [[ 1.  4.  9.]
 [16. 25. 36.]]


In [16]:
# Operation with scalr
# Multiplation/division/addition/subtraction/inverse
arr3 = 1 / arr
print("1/arr = ", arr3)

1/arr =  [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [17]:
# Taking power of each elemnt
arr4 = arr**0.5
print("arr**0.5= ", arr4)

arr**0.5=  [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [18]:
# comparison operation can also be compared with scalor 
arrA = np.array([[1.,2.,3.],[4.,5.,6.]])
arrB = np.array([[0.,4.,3.],[7.,1.,24.]])
print("arrA>arrB = ", arrA>arrB)

arrA>arrB =  [[ True False False]
 [False  True False]]


In [19]:
# genrate random array
a = np.random.randn((10))
b = np.random.randn((10))

In [20]:
a>0

array([ True,  True, False, False,  True,  True,  True, False, False,
        True])

In [21]:
a[a>0]

array([0.38176422, 0.50447558, 0.25921636, 0.09436436, 0.27826707,
       0.59678778])